### ISSUE TITLE
Error: Expected type utf8 for Argument 'schema_id' but got type 'undefined'

### ISSUE THREAD

**Issue by lovasoa** [al34034/Qwant-Gnome-shell-integration#10]
The function [`getSettings`](https://github.com/al34034/Qwant-Gnome-shell-integration/blob/feature/settings/Qwant_search%40alex.nitters.eu/convenience.js#L49) in `convenience.js` takes one argument (`schema`).

However, in [`prefs.js`, on line 41](https://github.com/al34034/Qwant-Gnome-shell-integration/blob/feature/settings/Qwant_search%40alex.nitters.eu/prefs.js#L41) it is called without arguments. In js, all parameters default to [`undefined`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined) when they are not set at the call site. [See this page on MDN about default parameter values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters).

This results in `SchemaSource.lookup` being called with a first argument value of `undefined`: 

https://github.com/al34034/Qwant-Gnome-shell-integration/blob/feature/settings/Qwant_search%40alex.nitters.eu/convenience.js#L70

**Comment by al34034** [comment]
[`getSettings`](https://github.com/al34034/Qwant-Gnome-shell-integration/blob/feature/settings/Qwant_search%40alex.nitters.eu/convenience.js#L49) should be called with the name of the schema as a string, but it still doesn't work. However, I cannot find anything about `utf8` arguments.
