### ISSUE TITLE
Sub optimal iteration on array elements

### ISSUE THREAD

**Issue by lovasoa** [al34034/Qwant-Gnome-shell-integration#3]
The following `for` loop recomputes the number of items in the array at each iteration:

https://github.com/al34034/Qwant-Gnome-shell-integration/blob/master/Qwant_search%40alex.nitters.eu/extension.js#L218-L229

It might be more judicious (and readable) to use [`Array.foreach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach). It would also allow to delete the `countProperties` function, that is used only here.

**Comment by lovasoa** [comment]
You might even want to do a simple

```js
qwantResults = new Map(suggestions.map(suggestion => {
    ...
}))

**Comment by al34034** [comment]
I'm using `suggestions.forEach` at the moment, which works, but with the map I get the error `invalid result meta`.

**Comment by lovasoa** [comment]
Hmm, did you return elements in the right format from your map function ?

It should look like 

```js
qwantResults = new Map(suggestions.map(suggestion => {
    ...
    const id = suggestion.url;
    const result = makeResult(...);
    return [id, result];
}))
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
