### ISSUE TITLE
the code mixes var and let

### ISSUE THREAD

**Issue by lovasoa** [al34034/Qwant-Gnome-shell-integration#4]
As your platform supports `let` and `const`, you might want to replace all the uses of `var` in the code, and try to replace as much `let` as possible by `const` to prevent accidental mutation of immutable variables.

**Comment by lovasoa** [comment]
MDN docs : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let

**Comment by lovasoa** [comment]
Tu aurais pu utiliser plus de `const`, non ?

**Comment by al34034** [comment]
En effet. Je viens de voir qu'on peut utiliser const pour une variable qui dépend d'une autre variable qui change, ce que je ne croyais pas possible. Je vais changer et vérifier que tout marche.

**Comment by lovasoa** [comment]
Très bien, bravo! Tu te rapproches de plus en plus de la programmation fonctionnelle !
