### ISSUE TITLE
use whole messages in gettext

### ISSUE THREAD

**Issue by lovasoa** [al34034/Qwant-Gnome-shell-integration#5]
https://github.com/al34034/Qwant-Gnome-shell-integration/blob/master/Qwant_search%40alex.nitters.eu/extension.js#L137

The use of two strings, with  `prepend` and `append` makes it more difficult for translators to understand and translate messages. It might be better to use something like

```js
_("search result message").replace("{search}", joined)
```

And use translation strings like `Rechercher "{search}" avec Qwant`

**Comment by al34034** [comment]
I've updated the code, but I will finish the translations first so everything works.
